services:
  fastify_api_db:
    image: postgres
    container_name: fastify_app_db
    restart: always
    environment:
      POSTGRES_USER: fastify_api
      POSTGRES_PASSWORD: fastify123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - fastify-api-network

  fastify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify_app
    environment:
      PORT: 8080
      PATH_API: "api/v1"
      DATABASE_URL: "postgresql://fastify_api:fastify123@fastify_app_db:5432/mydb?schema=fastify_api"
    ports:
      - "8080:8080"
    depends_on:
      - fastify_api_db
    networks:
      - fastify-api-network

networks:
  fastify-api-network:
    driver: bridge